all:
  children:

    linux:
      children:
        huawei_linux:

    windows:
      children:
        huawei_windows:

    huawei:
      children:

        huawei_linux:
          children:

            apeotactico-huawei:
            ayala-huawei:
            cortina-huawei:
            dacsa-huawei:
            dyn-huawei:
            enable-huawei:
            farmaamigo:
            grupo-edid:
            kenworth:
            marber-new:
            marnov-huawei:
            olmeca:
            sinergman-huawei:
            superdona:
            viko-new:   # 👈 🔥 ESTA ES LA CLAVE

        huawei_windows:
          children:
            # aquí van tus grupos de windows si tienes

    # =========================
    # DEFINICIÓN DE GRUPOS
    # =========================

    sinergman-huawei:
      hosts:
        sinergman-huawei-saprouter:
          ansible_host: 119.8.3.234
          ansible_user: root
          ansible_password: "{{ vault_sinergman-huawei-saprouter_password }}"

        sinergman-huawei-s4hana-pro:
          ansible_host: 119.8.2.18
          ansible_user: root
          ansible_password: "{{ vault_sinergman-huawei-s4hana-pro_password }}"

    viko-new:
      hosts:

        viko-new-pruebas-seguridad:
          ansible_host: 94.74.67.251

        viko-new-hana-cockpit:
          ansible_host: 94.74.70.83
          ansible_user: root
          ansible_password: "{{ vault_viko-new-hana-cockpit_password }}"

        viko-new-youlandapp:
          ansible_host: 94.74.71.43
          ansible_user: root
          ansible_password: "{{ vault_viko-new-youlandapp_password }}"

        viko-new-youlandbd-1:
          ansible_host: 94.74.66.66
          ansible_user: root
          ansible_password: "{{ vault_viko-new-youlandbd-1_password }}"

        viko-new-b1-hanapro:
          ansible_host: 101.44.24.95
          ansible_user: root
          ansible_password: "{{ vault_viko-new-b1-hanapro_password }}"

        viko-new-vikoweb:
          ansible_host: 101.44.187.68
          ansible_user: root
          ansible_password: "{{ vault_viko-new-vikoweb_password }}"
